apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: NEXUS_NAME
  value: nexus
- name: NEXUS_HOST
  description: Nexus host without protocol - which is attached based on the configuration in the route.yml
  required: true
objects:
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${NEXUS_NAME}
    name: ${NEXUS_NAME}
  spec:
    host: ${NEXUS_HOST}
    port:
      targetPort: 8081-tcp
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: ${NEXUS_NAME}
      weight: 100
    wildcardPolicy: None
