apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: NEXUS_NAME
  value: nexus
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NEXUS_NAME}
    name: ${NEXUS_NAME}
  spec:
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      deploymentconfig: ${NEXUS_NAME}
    sessionAffinity: None
    type: ClusterIP
