apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: aqua-db-pvc
  namespace: aqua
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: aqua-audit-db-pvc
  namespace: aqua
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
