apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aqua-gateway
  name: aqua-gateway
  namespace: aqua
spec:
  ports:
  - name: aqua-gateway-ssl
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: aqua-gateway
    port: 3622
    protocol: TCP
    targetPort: 3622
  selector:
    app: aqua-gateway
  type: LoadBalancer
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: aqua-web
  name: aqua-web
  namespace: aqua
spec:
  ports:
  - name: aqua-web-ssl
    port: 443
    protocol: TCP
    targetPort: 8443
  - name: aqua-web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: aqua-web
  type: LoadBalancer
status:
  loadBalancer: {}
