apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: CD_USER_PWD_B64
    description: cd_user password (base64 encoded)
    required: true
  - name: CD_USER_ID_B64
    description: cd_user name (base64 encoded)
    required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: cd-user-token
    labels:
      template: cd-user-template
  type: kubernetes.io/basic-auth
  data:
    password: ${CD_USER_PWD_B64}
    username: ${CD_USER_ID_B64}
